/*
Design a Log Ingestion Pipeline that efficiently processes logs generated by
multiple producer threads. The pipeline should: Accept log messages from
multiple producers concurrently. Store incoming logs in a thread-safe queue. Use
a background worker thread to consume logs. Process logs in fixed-size batches.
Forward each batch to a pluggable sink (e.g., Console, File, Kafka).
Shut down gracefully, ensuring all queued logs are processed before exiting.

Architecture:
Producer Threads
       │
       ▼
Thread-safe Queue
       │
Condition Variable
       │
       ▼
Pipeline Worker
       │
Collect Batch (N logs)
       │
       ▼
(Console/File/Kafka) Sink

Complexity: TC = SC = O(N)
N = number of queued logs
B = batch size (constant in this implementation)

Production Enhancements:
Time-based batch flushing (e.g., every 100 ms)
Multiple consumer threads
Bounded queue and backpressure
File, Kafka, or database sinks
Structured log parsing (JSON/Protobuf)
Log filtering by severity
Retry mechanisms and dead-letter queues
Metrics, monitoring, and rate limiting
*/

#include <condition_variable>
#include <iostream>
#include <mutex>
#include <queue>
#include <string>
#include <thread>
#include <vector>
using namespace std;

//----------Sink-----------------------
class Sink {
public:
  virtual void write(const vector<string> &logs) = 0;
  virtual ~Sink() = default;
};

class ConsoleSink : public Sink {
public:
  void write(const vector<string> &logs) override {
    cout << "Processing Batch : (" << logs.size() << "Logs) \n";
    for (const auto &log : logs)
      cout << log << endl;
  }
};

//---------Pipeline--------------------
class LogPipeline {
private:
  queue<string> log_queue;

  mutex mtx;
  condition_variable cv;

  bool stop = false;

  thread worker;

  Sink *sink;
  const int BATCH_SIZE = 3;

  void process_logs() {

    while (true) {

      vector<string> batch;
      {
        unique_lock<mutex> lock(mtx);
        cv.wait(lock, [&]() { return stop || !log_queue.empty(); });

        // Graceful shutdown
        if (stop == true && log_queue.empty())
          break;

        // VVIMP: collect logs from queue in batches
        while (!log_queue.empty() && batch.size() < BATCH_SIZE) {
          batch.push_back(log_queue.front());
          log_queue.pop();
        }
      }
      // once batch is Full, flush it to Console
      sink->write(batch);
    }
  }

public:
  LogPipeline(Sink *s) : sink(s) {
    worker = thread(&LogPipeline::process_logs, this);
  }

  void ingest(const string &log) {
    { // push log into log_queue
      lock_guard<mutex> lock(mtx);
      log_queue.push(log);
    }
    cv.notify_one(); // notify process_logs() thread
  }

  ~LogPipeline() {
    {
      lock_guard<mutex> lock(mtx);
      stop = true;
    }
    cv.notify_all();

    worker.join();
  }
};

int main() {

  ConsoleSink sink;
  LogPipeline pipeline(&sink);

  thread t1([&]() {
    for (int i = 1; i <= 5; i++)
      pipeline.ingest("INFO: Login " + to_string(i));
  });

  thread t2([&]() {
    for (int i = 1; i <= 5; i++)
      pipeline.ingest("ERROR : DB " + to_string(i));
  });

  t1.join();
  t2.join();

  return 0;
}
/*
Output:
Processing Batch : (3Logs)
INFO: Login 1
ERROR : DB 1
ERROR : DB 2
Processing Batch : (3Logs)
ERROR : DB 3
ERROR : DB 4
ERROR : DB 5
Processing Batch : (3Logs)
INFO: Login 2
INFO: Login 3
INFO: Login 4
Processing Batch : (1Logs)
INFO: Login 5

Improvement for Production:
Replace ConsoleSink with FileSink, KafkaSink, or DatabaseSink.
Add time-based batching (flush after 100 ms even if the batch isn't full).
Use a bounded queue for backpressure.
Support multiple consumer threads.
Parse structured (e.g., JSON) logs and filter by severity.
Add retries, metrics, and monitoring.
*/
